# Generated by Django 5.2.1 on 2025-06-25 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
