# Generated by Django 5.2.1 on 2025-06-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitApp', '0002_remove_userprofile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_workout',
            name='id',
        ),
        migrations.AlterField(
            model_name='add_workout',
            name='workout_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
